name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to tag image with'
        required: true
        default: '0.0.1'

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          build-args: |
            Version=${{ github.event.inputs.version }}
          tags: |
            ghcr.io/prokleta-kuja/ircica:latest
            ghcr.io/prokleta-kuja/ircica:${{ github.event.inputs.version }}
